export enum RecipeCreateStatus {
  VIDEO_ANALYSIS = "VIDEO_ANALYSIS",
  INGREDIENTS_ANALYSIS = "INGREDIENTS_ANALYSIS",
  COOKING_STEPS_ANALYSIS = "COOKING_STEPS_ANALYSIS",
  COMPLETED = "COMPLETED",
}
