import { UnCategorizedRecipeApiResponse } from "./api";

export const categoryRecipesApiMock: Record<
  string,
  UnCategorizedRecipeApiResponse
> = {
  "1": {
    recipe_id: "1",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 1,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "한식",
    category_id: "1",
  },
  "2": {
    recipe_id: "2",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "한식",
    category_id: "1",
  },
  "3": {
    recipe_id: "3",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "양식",
    category_id: "2",
  },
  "4": {
    recipe_id: "4",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "5": {
    recipe_id: "5",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "6": {
    recipe_id: "6",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "7": {
    recipe_id: "7",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "8": {
    recipe_id: "8",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "9": {
    recipe_id: "9",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "10": {
    recipe_id: "10",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "11": {
    recipe_id: "11",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "12": {
    recipe_id: "12",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "13": {
    recipe_id: "13",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "14": {
    recipe_id: "14",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "15": {
    recipe_id: "15",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "16": {
    recipe_id: "16",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "17": {
    recipe_id: "17",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "18": {
    recipe_id: "18",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "19": {
    recipe_id: "19",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "20": {
    recipe_id: "20",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "21": {
    recipe_id: "21",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "22": {
    recipe_id: "22",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "23": {
    recipe_id: "23",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "24": {
    recipe_id: "24",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "25": {
    recipe_id: "25",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
  "26": {
    recipe_id: "26",
    recipe_title: "백종원의 제육볶음",
    video_id: "j7s9VRsrm9o",
    video_thumbnail_url: "https://img.youtube.com/vi/j7s9VRsrm9o/hqdefault.jpg",
    last_play_seconds: 50,
    viewed_at: "2023-10-01T12:00:00Z",
    video_seconds: 120,
    category: "미분류",
    category_id: "3",
  },
};

export function categoryRecipesMock(): UnCategorizedRecipeApiResponse[] {
  return Object.values(categoryRecipesApiMock);
}
